/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-zint.h
 #	source generated by 4D Plugin Wizard
 #	Project : zint
 #	author : miyako
 #	2019/11/26
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ZINT_H
#define PLUGIN_ZINT_H

#include "4DPluginAPI.h"

#include "zint.h"
#include "png.h"
#include "zlib.h"
#include "font.h"
#include "maxipng.h"

#pragma mark -

#define ZINT_HEIGHT 1
#define ZINT_WHITE_SPACE 2
#define ZINT_BORDER 3
#define ZINT_BOX 4
#define ZINT_BIND 5
#define ZINT_SCALE 9
#define ZINT_ROTATE 10
#define ZINT_COLUMNS 11
#define ZINT_VERSION 12
#define ZINT_SECURE 13
#define ZINT_PRIMARY 14
#define ZINT_MODE 15
#define ZINT_GS1 16
#define ZINT_NO_TEXT 17
#define ZINT_SQUARE 18
#define ZINT_KANJI 19
#define ZINT_SJIS 20
#define ZINT_SMALL_TEXT 21
#define ZINT_DPI 22
#define ZINT_NO_BACKGROUND 23

#define ZINT_OUTPUT_SVG 1
#define ZINT_OUTPUT_PNG 2

#include "4DPlugin-JSON.h"

void ZINT(PA_PluginParameters params);

#include "png.h"

#define INCHES_PER_METER (100.0/2.54)

#include "C_TEXT.h"
#include "C_BLOB.h"

#ifdef _WIN32
extern "C" { FILE __iob_func[3] = { *stdin,*stdout,*stderr }; }
#endif

void toSVG(zint_symbol *symbol, int dpi, int rotate_angle, bool no_background, PA_ObjectRef o);
void toPNG(zint_symbol *symbol, int dpi, int rotate_angle, bool no_background, PA_ObjectRef o);

void write_data_fn(png_structp png_ptr, png_bytep buf, png_size_t size);
void output_flush_fn(png_structp png_ptr);

#endif /* PLUGIN_ZINT_H */
